apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wsrestlogin-deployment
  namespace: dev
  labels:
    app: wsrestlogin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wsrestlogin
  template:
    metadata:
      labels:
        app: wsrestlogin
    spec:
      containers:
        - name: wsrestlogin
          image: sophosstore/wsrestlogin:beta
          ports:
          - containerPort: 18081
          command: [ "/bin/sh", "-c", "ls /etc/config/" ]
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: wsrestlogin-configmap
